#!/usr/bin/env python3
"""Operator and sector-area playbook definitions backed by researched industry slugs."""

PLAYBOOKS = [
    {
        "slug": "local-services-rollup",
        "title": "The Local Services Rollup",
        "lens": "Main Street Services",
        "thesis": "Fragmented local service categories become better businesses when scheduling, pricing, labor, and marketing are centralized.",
        "slugs": [
            "hair-and-nail-salons-in-the-us",
            "hair-salons",
            "gym-and-fitness-franchises",
            "gym-health-and-fitness-clubs-in-the-us",
            "hvac-service-franchises",
            "handyman-service-franchises",
            "janitorial-services-in-the-us",
            "dance-studios",
            "health-and-wellness-spas",
            "massage-franchises",
        ],
        "operator_questions": [
            "Can dispatch, booking, marketing, and procurement be centralized without killing local demand?",
            "Is labor scarce enough that recruiting and retention are the real moat?",
            "Can price increases be passed through without churn?",
        ],
    },
    {
        "slug": "specialty-manufacturer",
        "title": "The Specialty Manufacturer",
        "lens": "Industrial Operators",
        "thesis": "Small industrial manufacturers can be defensible when they make narrow, specified products that customers cannot easily substitute.",
        "slugs": [
            "laboratory-casework-manufacturing",
            "laboratory-fume-hoods-manufacturing",
            "industrial-and-fluid-power-valve-manufacturing",
            "industrial-and-commercial-fan-and-blower-manufacturing",
            "commercial-oven-manufacturing",
            "dental-clinical-instrument-manufacturing",
            "drug-and-alcohol-test-kit-manufacturing",
            "cotton-personal-care-product-manufacturing",
            "laminated-plastics-manufacturing-in-the-us",
            "lighting-fixtures-manufacturing-in-the-us",
        ],
        "operator_questions": [
            "Is demand driven by replacement, regulation, or specification rather than discretionary volume?",
            "Can automation or procurement improve margin without new plant risk?",
            "Are tariffs and input costs pass-throughable?",
        ],
    },
    {
        "slug": "health-services-operator",
        "title": "The Health Services Operator",
        "lens": "Healthcare Delivery",
        "thesis": "Healthcare service operators win when they manage reimbursement, staffing, referral flow, and compliance better than local independents.",
        "slugs": [
            "elderly-and-disabled-services-in-the-us",
            "eating-disorder-clinics",
            "dna-and-dna-forensic-laboratories",
            "laboratory-testing-services-in-the-us",
            "hearing-aid-clinics",
            "healthcare-staff-recruitment-agencies",
            "healthcare-consultants",
            "hospices-and-palliative-care-centers",
            "in-home-senior-care-franchises",
            "dental-equipment-dealers",
        ],
        "operator_questions": [
            "Is payer mix improving or deteriorating?",
            "Can clinician and caregiver labor be recruited reliably?",
            "Does compliance complexity favor scale?",
        ],
    },
    {
        "slug": "experiential-venue",
        "title": "The Experiential Venue",
        "lens": "Consumer Experience",
        "thesis": "Experience businesses survive the channel shift when the venue itself is the product and utilization can be managed tightly.",
        "slugs": [
            "arcade-food-and-entertainment-complexes-in-the-us",
            "dance-studios",
            "karaoke-bars",
            "golf-driving-ranges-and-family-fun-centers-in-the-us",
            "indoor-climbing-walls",
            "indoor-sports-facilities-management",
            "ice-rinks",
            "boxing-gyms-and-clubs",
            "convention-and-visitor-bureaus-in-the-us",
            "cruise-and-travel-agency-franchises",
        ],
        "operator_questions": [
            "Can utilization be smoothed across weekdays and seasons?",
            "Does the concept have local scarcity or is it easy to copy?",
            "Are labor, insurance, and rent rising faster than ticket yield?",
        ],
    },
    {
        "slug": "food-production-niche",
        "title": "The Food Production Niche",
        "lens": "Food & Beverage",
        "thesis": "Niche food producers live between health-driven demand shifts, input-cost volatility, and retailer/wholesaler bargaining power.",
        "slugs": [
            "cocoa-and-drinking-chocolate-production",
            "coffee-creamer-production",
            "kombucha-production-in-the-us",
            "hot-sauce-production",
            "bbq-sauce-production",
            "cider-production",
            "doughnut-stores",
            "dairy-farms-in-the-us",
            "dairy-wholesaling-in-the-us",
            "egg-and-poultry-wholesaling-in-the-us",
        ],
        "operator_questions": [
            "Is this product riding health, premium, convenience, or indulgence?",
            "Can input swings be hedged or passed through?",
            "Does distribution create the moat or the squeeze?",
        ],
    },
    {
        "slug": "regulated-admin-stack",
        "title": "The Regulated Admin Stack",
        "lens": "Compliance Infrastructure",
        "thesis": "Complexity creates businesses: testing, claims, identity, forensic work, HR, and compliance software turn regulation into recurring demand.",
        "slugs": [
            "insurance-claims-processing-software",
            "identity-management-software-in-the-us",
            "identity-theft-protection-services",
            "forensic-accounting-services",
            "forensic-technology-services",
            "dna-and-dna-forensic-laboratories",
            "drug-and-alcohol-test-kit-manufacturing",
            "hr-and-payroll-software",
            "it-security-consulting",
            "education-consultants",
        ],
        "operator_questions": [
            "Is the work mandatory, recurring, and hard to defer?",
            "Can AI reduce fulfillment cost without increasing liability?",
            "Are customers buying risk reduction or just a cheaper workflow?",
        ],
    },
    {
        "slug": "distribution-middleman",
        "title": "The Distribution Middleman",
        "lens": "Wholesale & Distribution",
        "thesis": "Distribution businesses are attractive when inventory, credit, technical knowledge, or local availability makes the middleman hard to remove.",
        "slugs": [
            "electrical-equipment-wholesaling-in-the-us",
            "coal-and-ore-wholesaling-in-the-us",
            "dairy-wholesaling-in-the-us",
            "egg-and-poultry-wholesaling-in-the-us",
            "janitorial-equipment-supply-wholesaling-in-the-us",
            "jewelry-and-watch-wholesaling-in-the-us",
            "laboratory-supply-wholesaling-in-the-us",
            "industrial-machinery-and-equipment-wholesaling-in-the-us",
            "industrial-supplies-wholesaling-in-the-us",
            "footwear-wholesaling-in-the-us",
        ],
        "operator_questions": [
            "Is the distributor providing credit, speed, expertise, or just taking a margin?",
            "Can procurement scale improve gross margin?",
            "Which customers can bypass the channel?",
        ],
    },
    {
        "slug": "care-and-family-infrastructure",
        "title": "Care & Family Infrastructure",
        "lens": "Societal Services",
        "thesis": "Aging households, working parents, and health complexity create durable demand for care businesses, but labor and regulation cap returns.",
        "slugs": [
            "elderly-and-disabled-services-in-the-us",
            "early-childhood-learning-centers",
            "child-education-and-developmental-center-franchises",
            "family-counseling-and-crisis-intervention-services-in-the-us",
            "family-planning-and-abortion-clinics-in-the-us",
            "in-home-senior-care-franchises",
            "hospices-and-palliative-care-centers",
            "home-medical-equipment-rentals",
            "health-and-welfare-funds-in-the-us",
            "eating-disorder-clinics",
        ],
        "operator_questions": [
            "Is demand demographic, cyclical, or policy-driven?",
            "Where is the staffing bottleneck?",
            "Does regulation protect scaled operators or punish them?",
        ],
    },
]
